name: Docker Image CI - release

on:
  push:
    tags:
      - v**
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get current date
        id: date
        run: |
          echo "timestamp=$(date +'%s')" >> $GITHUB_ENV
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gojuukaze/grasscutter
          tags: |
            type=sha,enable=false,priority=100,prefix=test-,suffix=${{ env.date }},format=short
            type=raw,enable=false,priority=200,prefix=test-,suffix=,value=${{ env.timestamp }}
            type=ref,enable=true,priority=300,event=tag,suffix=-${{ env.date }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
